import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Session from "@/components/next-auth.provider";
import SearchInputContextProvider from "@/utils/search/search-context";
import ReduxProvider from "@/components/ReduxProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MobilUX",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div>
          <ReduxProvider>
            <Session>
              <SearchInputContextProvider>
                <Header />
                {children}
                <Footer />
              </SearchInputContextProvider>
            </Session>
          </ReduxProvider>
        </div>
      </body>
    </html>
  );
}
